// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUdevRules(arg1:number,arg2:number):Promise<boolean>;

export function DetectDevice():Promise<main.Device>;

export function FlashFirmware(arg1:main.Device,arg2:string,arg3:number):Promise<main.FlashResult>;

export function GetAppIcon():Promise<string>;

export function GetEmbeddedFirmware(arg1:string):Promise<string>;

export function GetKeyboardImage(arg1:main.Device):Promise<string>;

export function GetSonixFlasherPath():Promise<string>;

export function GetUdevRulesContent():Promise<string>;

export function SelectFirmware():Promise<string>;
