// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUdevRules(arg1, arg2) {
  return window['go']['main']['App']['CheckUdevRules'](arg1, arg2);
}

export function DetectDevice() {
  return window['go']['main']['App']['DetectDevice']();
}

export function FlashFirmware(arg1, arg2, arg3) {
  return window['go']['main']['App']['FlashFirmware'](arg1, arg2, arg3);
}

export function GetAppIcon() {
  return window['go']['main']['App']['GetAppIcon']();
}

export function GetEmbeddedFirmware(arg1) {
  return window['go']['main']['App']['GetEmbeddedFirmware'](arg1);
}

export function GetKeyboardImage(arg1) {
  return window['go']['main']['App']['GetKeyboardImage'](arg1);
}

export function GetSonixFlasherPath() {
  return window['go']['main']['App']['GetSonixFlasherPath']();
}

export function GetUdevRulesContent() {
  return window['go']['main']['App']['GetUdevRulesContent']();
}

export function SelectFirmware() {
  return window['go']['main']['App']['SelectFirmware']();
}
